app_env: development

logconf:
  log_path: "./logs/boilerplate-api.log"
  panic_log_path: "./logs/stderr-binxin-api.log"
  log_level: "INFO"
  log_type: "file"
  max_size_mb: 512       # Rotate after 512MB
  max_backups: 8         # Keep 8 backup logs
  max_age_days: 30       # Keep logs for 30 days, use 0 for infinite days
  compress: true         # Compress rotated logs

server:
  port: 8080

jwt:
  secret: "secret"
  access_token_expiration_time: 3600
  refresh_token_expiration_time: 86400

mongodb:
  host: "localhost"
  port: 27017
  user: "admin"
  password: "password"
  db_name: "boilerplate"
  ssl_mode: "disable"

mysql:
  host: "localhost"
  port: 3306
  user: "admin"
  password: "password"
  db_name: "boilerplate"
  ssl_mode: "disable"

redis:
  host: "localhost"
  port: 6379
  password: ""
  number_channel_room: "3"

minio:
  host: "localhost"
  user: "user"
  password: "password"
  access_key: "access_key"
  secret_key: "secret_key"
  bucket: "bucket"
  use_ssl: false

easemob:
  org_name: "1176250311225722"
  app_name: "boilerplate"
  client_id: "YXA6Bcn3umw-RlqbLXXo-Zp9Uw"
  client_secret: "YXA6wPaem3gWgaqBPquU4lhYbad4CNI"
  app_key: "1176250311225722#boilerplate"
  base_url: "https://a1.easemob.com"
